// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcceptOneTime(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1606092712, sessionID);
}

/**
 * CancelPetMotion stops an in-progress expand or collapse animation. Dragging
 * calls this before handing control to the native window manager.
 */
export function CancelPetMotion(): $CancellablePromise<void> {
    return $Call.ByID(4195178976);
}

export function CancelSend(sendID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2554164107, sendID);
}

export function CancelTransportSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1280695090, sessionID);
}

export function CheckForUpdate(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1094046213);
}

export function CheckSSH(input: $models.SSHSettingsInput): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(27151125, input);
}

export function ChooseFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3665540653);
}

export function ChooseFolder(): $CancellablePromise<string> {
    return $Call.ByID(1460320850);
}

export function ChooseInbox(): $CancellablePromise<string> {
    return $Call.ByID(3353811010);
}

export function ClearRecent(): $CancellablePromise<void> {
    return $Call.ByID(1651455851);
}

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(3358856085);
}

export function CreateOneTime(paths: string[] | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(963152884, paths);
}

export function CreateSSHPairing(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(949770729);
}

export function CrossNetworkConfig(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3432393247);
}

/**
 * DisablePet is the pet context menu's "关闭桌宠": hide the widget and
 * persist showPet=false, exactly like unticking the settings toggle. The
 * app keeps running in the tray.
 */
export function DisablePet(): $CancellablePromise<void> {
    return $Call.ByID(901081746);
}

/**
 * DragPet performs a native window drag and returns when the mouse button is
 * released. performWindowDragWithEvent hands the window to the window server
 * and returns immediately, so the release boundary must come from polling the
 * global button state — the WebView never sees the mouseup once the native
 * drag owns the event stream, and returning early made snap() fight the
 * still-running drag from the start position.
 */
export function DragPet(): $CancellablePromise<void> {
    return $Call.ByID(3952069318);
}

export function GetConfig(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2299530779);
}

/**
 * GetPetScreenArea returns the current screen in the same logical coordinate
 * space as WebviewWindow.Position. Wails alpha2.117's macOS GetScreen path
 * skips ScreenManager's DPI conversion, so normalise its raw Retina values
 * here instead of mixing them with logical window coordinates.
 */
export function GetPetScreenArea(): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(1654588883);
}

export function GetSelected(): $CancellablePromise<string> {
    return $Call.ByID(2964859496);
}

export function JoinOneTime(code: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(774114716, code);
}

export function JoinSSHPairing(code: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3582432961, code);
}

export function ManualPeers(): $CancellablePromise<$models.ManualPeerConfig[] | null> {
    return $Call.ByID(3580292482);
}

/**
 * MovePetTo animates the native window position independently of WebView
 * rendering. A WebView can stop requestAnimationFrame after most of a
 * transparent window leaves the screen, which otherwise strands the pet
 * halfway through its collapsed position.
 */
export function MovePetTo(x: number, y: number, durationMS: number): $CancellablePromise<void> {
    return $Call.ByID(1723196142, x, y, durationMS);
}

export function OpenInbox(): $CancellablePromise<void> {
    return $Call.ByID(3310189257);
}

export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(4119985044, path);
}

export function OpenReleases(): $CancellablePromise<void> {
    return $Call.ByID(1155708841);
}

export function OpenRepository(): $CancellablePromise<void> {
    return $Call.ByID(322226103);
}

export function Peers(): $CancellablePromise<$models.PeerView[] | null> {
    return $Call.ByID(1667773428);
}

export function RecentFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2597322811);
}

export function RejectOneTime(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(776819465, sessionID);
}

export function RemoveSSHPeer(instanceID: string): $CancellablePromise<void> {
    return $Call.ByID(3599902979, instanceID);
}

export function SaveConfig(peerName: string, inbox: string, secret: string, clearSecret: boolean, port: number, showPet: boolean, encryptionEnabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(236602228, peerName, inbox, secret, clearSecret, port, showPet, encryptionEnabled);
}

export function SaveManualPeers(peers: $models.ManualPeerConfig[] | null): $CancellablePromise<void> {
    return $Call.ByID(74294601, peers);
}

export function SaveSSHConfig(input: $models.SSHSettingsInput): $CancellablePromise<void> {
    return $Call.ByID(1643904814, input);
}

export function SaveWormholeConfig(rendezvousURL: string, transitRelay: string): $CancellablePromise<void> {
    return $Call.ByID(2778361349, rendezvousURL, transitRelay);
}

export function SelectPeer(instanceID: string): $CancellablePromise<void> {
    return $Call.ByID(3137040255, instanceID);
}

export function SendPaths(instanceID: string, paths: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(3022705747, instanceID, paths);
}

export function SendToSelected(paths: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(519415057, paths);
}

export function SetPetVisible(visible: boolean): $CancellablePromise<void> {
    return $Call.ByID(2827133472, visible);
}

export function ShowMain(): $CancellablePromise<void> {
    return $Call.ByID(274662635);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3502938117);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(4248441943);
}
