// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ManualPeerConfig {
    "name": string;
    "host": string;
    "port": number;
    "instance_id"?: string;
    "fingerprint"?: string;
}

export interface PeerView {
    "instanceId": string;
    "name": string;
    "host": string;
    "port": number;
    "fingerprint": string;
    "transport": string;
    "routes": string[] | null;
    "capabilities"?: string[] | null;
}

export interface SSHPeerConfig {
    "id": string;
    "name": string;
    "instance_id": string;
    "remote_port": number;
    "noise_public": string;
    "end_to_end": boolean;
}

export interface SSHSettingsInput {
    "enabled": boolean;
    "host": string;
    "port": number;
    "user": string;
    "privateKeyMode": string;
    "privateKeyPath": string;
    "pastedKey": string;
    "passphrase": string;
    "clearPassphrase": boolean;
    "hostKeySHA256": string;
    "peers": SSHPeerConfig[] | null;
}
