package lan

import (
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"net"
	"strings"
	"testing"
	"time"
)

// Vectors generated by the Python reference implementation
// (inkhole.device_identity) so the Go stack stays byte-compatible.
const (
	pyPrivateKey = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgVO6arM+PAd3a42pmb509ubtPDYoE9d9mdMCYp0HfYK6hRANCAARy+pdDHUETkZ53R/srorvGwti8iqRYCmipuQyBWr2wz754jDJKtHO+s05RsyZeg7WOlD1MBs5OCMSPtYfmGP60"
	pyPublicKey  = "BHL6l0MdQRORnndH+yuiu8bC2LyKpFgKaKm5DIFavbDPvniMMkq0c76zTlGzJl6DtY6UPUwGzk4IxI+1h+YY/rQ="
	pyFP         = "a23daef627779c971fd066bc8b873dc74d1fe00626c55d55cf4534f231357dc0"
	pyMsgHex     = "494e4b484f4c452d574850433300000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f00036131623263336434653566366137623861316232633364346535663661376238000ae5a2a8e6b49e2d4d616300020009666f6c6465722d7631000b72656c6961626c652d7633"
	pySignature  = "MEUCIQCleKJGO2YWjS0KBBx4tpMaxufT/4L35efGvC7KIIcR9QIgc9nFVhCGZF44F+un1p3AeHyGUUZVFn65uV7fw4y1bkM="

	vecInstanceID = "a1b2c3d4e5f6a7b8a1b2c3d4e5f6a7b8"
	vecPeerName   = "墨洞-Mac"
)

func vecNonce() []byte {
	nonce := make([]byte, 32)
	for i := range nonce {
		nonce[i] = byte(i)
	}
	return nonce
}

func TestCapabilityMessageMatchesPython(t *testing.T) {
	// Duplicate + unsorted caps must normalize identically to Python's
	// sorted-set encoding; uppercase instance ids are lowered.
	message, err := CapabilityMessage(vecNonce(), strings.ToUpper(vecInstanceID),
		vecPeerName, CapVersion, []string{"reliable-v3", "folder-v1", "reliable-v3"})
	if err != nil {
		t.Fatalf("CapabilityMessage: %v", err)
	}
	if got := hex.EncodeToString(message); got != pyMsgHex {
		t.Fatalf("capability message mismatch:\n got %s\nwant %s", got, pyMsgHex)
	}
}

func TestVerifyPythonSignature(t *testing.T) {
	message, err := hex.DecodeString(pyMsgHex)
	if err != nil {
		t.Fatal(err)
	}
	if !Verify(pyPublicKey, message, pySignature) {
		t.Fatal("Python-produced signature failed Go verification")
	}
	if Verify(pyPublicKey, append(message, 'x'), pySignature) {
		t.Fatal("tampered message passed verification")
	}
}

func TestIdentityFromPythonPrivateKey(t *testing.T) {
	identity, err := IdentityFromPrivateKey(pyPrivateKey)
	if err != nil {
		t.Fatalf("IdentityFromPrivateKey: %v", err)
	}
	if identity.PublicKey != pyPublicKey {
		t.Fatalf("public key mismatch:\n got %s\nwant %s",
			identity.PublicKey, pyPublicKey)
	}
	if identity.Fingerprint != pyFP {
		t.Fatalf("fingerprint mismatch: %s != %s", identity.Fingerprint, pyFP)
	}
	message, _ := hex.DecodeString(pyMsgHex)
	signature, err := identity.Sign(message)
	if err != nil {
		t.Fatalf("Sign: %v", err)
	}
	if !Verify(identity.PublicKey, message, signature) {
		t.Fatal("own signature failed verification")
	}
	exported, err := identity.ExportPrivateKey()
	if err != nil {
		t.Fatalf("ExportPrivateKey: %v", err)
	}
	reloaded, err := IdentityFromPrivateKey(exported)
	if err != nil {
		t.Fatalf("reload exported key: %v", err)
	}
	if reloaded.Fingerprint != identity.Fingerprint {
		t.Fatal("exported key round-trip changed the fingerprint")
	}
}

func TestPublicFingerprintRejectsBadKeys(t *testing.T) {
	if _, err := PublicFingerprint("not-base64!"); err == nil {
		t.Fatal("invalid base64 accepted")
	}
	if _, err := PublicFingerprint("AAAA"); err == nil {
		t.Fatal("short key accepted")
	}
	if got, err := PublicFingerprint(pyPublicKey); err != nil || got != pyFP {
		t.Fatalf("PublicFingerprint = %s, %v; want %s", got, err, pyFP)
	}
}

func TestValidInstanceID(t *testing.T) {
	if !ValidInstanceID(vecInstanceID) {
		t.Fatal("valid id rejected")
	}
	for _, bad := range []string{"", "abc", strings.ToUpper(vecInstanceID),
		"g1b2c3d4e5f6a7b8a1b2c3d4e5f6a7b8"} {
		if ValidInstanceID(bad) {
			t.Fatalf("invalid id accepted: %q", bad)
		}
	}
}

func startProbeServer(t *testing.T, identity *Identity,
	instanceID, peerName string, caps []string) *net.TCPAddr {
	t.Helper()
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("listen: %v", err)
	}
	t.Cleanup(func() { _ = listener.Close() })
	go func() {
		for {
			conn, err := listener.Accept()
			if err != nil {
				return
			}
			go func(conn net.Conn) {
				defer conn.Close()
				_ = conn.SetDeadline(time.Now().Add(5 * time.Second))
				head := make([]byte, 4)
				if _, err := io.ReadFull(conn, head); err != nil ||
					string(head) != capMagic {
					return
				}
				_ = RespondProbe(conn, identity, instanceID, peerName, caps)
			}(conn)
		}
	}()
	return listener.Addr().(*net.TCPAddr)
}

func TestProbeLoopback(t *testing.T) {
	identity, err := GenerateIdentity()
	if err != nil {
		t.Fatal(err)
	}
	caps := []string{"folder-v1", "reliable-v3"}
	addr := startProbeServer(t, identity, vecInstanceID, "回环设备", caps)
	result, err := ProbePeer("127.0.0.1", addr.Port, 3*time.Second, "")
	if err != nil {
		t.Fatalf("ProbePeer: %v", err)
	}
	if result.InstanceID != vecInstanceID || result.PeerName != "回环设备" {
		t.Fatalf("unexpected result: %+v", result)
	}
	if result.Fingerprint != identity.Fingerprint {
		t.Fatal("fingerprint mismatch")
	}
	if result.ConnectedIP != "127.0.0.1" {
		t.Fatalf("connected ip = %s", result.ConnectedIP)
	}
	// Pinning a different instance id must fail as an identity error.
	_, err = ProbePeer("127.0.0.1", addr.Port, 3*time.Second,
		"ffffffffffffffffffffffffffffffff")
	if !errors.Is(err, ErrIdentityMismatch) {
		t.Fatalf("expected identity mismatch, got %v", err)
	}
}

func TestProbeRejectsWrongNonceSignature(t *testing.T) {
	signer, err := GenerateIdentity()
	if err != nil {
		t.Fatal(err)
	}
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = listener.Close() })
	go func() {
		conn, err := listener.Accept()
		if err != nil {
			return
		}
		defer conn.Close()
		_ = conn.SetDeadline(time.Now().Add(5 * time.Second))
		head := make([]byte, 36)
		if _, err := io.ReadFull(conn, head); err != nil {
			return
		}
		// Sign over a zero nonce instead of the client's challenge: the
		// answer is well-formed but must fail signature verification.
		wrongNonce := make([]byte, 32)
		message, _ := CapabilityMessage(
			wrongNonce, vecInstanceID, "假设备", CapVersion, []string{})
		signature, _ := signer.Sign(message)
		raw, _ := json.Marshal(probeBody{
			Version:    CapVersion,
			Caps:       []string{},
			InstanceID: vecInstanceID,
			PeerName:   "假设备",
			PublicKey:  signer.PublicKey,
			Signature:  signature,
		})
		out := append([]byte(capMagic),
			binary.BigEndian.AppendUint32(nil, uint32(len(raw)))...)
		out = append(out, raw...)
		_, _ = conn.Write(out)
	}()
	addr := listener.Addr().(*net.TCPAddr)
	_, err = ProbePeer("127.0.0.1", addr.Port, 3*time.Second, "")
	if !errors.Is(err, ErrIdentityMismatch) {
		t.Fatalf("expected identity mismatch, got %v", err)
	}
}
